export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const CLOSE_NOTIFICATION_MODAL = "CLOSE_NOTIFICATION_MODAL";
